### ISSUE TITLE
Unable read xlsx data in Spout with custom PHP stream wrapper (with oneup flystyem)

### ISSUE THREAD

**Issue by v20100v** [box/spout#718]
In a symfony project, i use oneup flystem with a custom stream wrapper name "pj" configure like this.

```
# /config/packages/oneup_flysystem.yaml

# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
  adapters:
    my_adapter:
      local:
        directory: "%kernel.project_dir%/var/uploads"
        permissions:
          file:
            # Fix. for windows... otherwise stream_wrapper fail to recognize the file as public.
            public: 438

  filesystems:
    my_filesystem:
      adapter: my_adapter
      alias: League\Flysystem\Filesystem
      # Allows to read files with any stream function using "pj:/path/of/file/in/flysystem"
      stream_wrapper: pj
```

For example in a symfony controller, i use this stream wrapper without problem like this

```php
    /**
     * @Route("/attachment-files/download/{id}", name="download_attachment_file", methods={"GET"})
     */
    public function downloadAttachmentFile(AttachmentFile $attachmentFile): Response
    {
        return $this->file(
            \sprintf('pj://%s', $attachmentFile->getPathFileName()),
            $attachmentFile->getFileName(),
            ResponseHeaderBag::DISPOSITION_ATTACHMENT
        );
    }
```

I would like use spout to parse and get data in Excel file. I use it like this

```
    public function extractExcelSheetIndicators(FlysystemFile $file): ?array
    {
        if ($file->getExtension() === 'xlsx') {
            $filePathname = 'pj://' . $file->getPathname();
            $reader = ReaderEntityFactory::createReaderFromFile($filePathname);
            $reader->open($filePathname);

            /** @var Sheet $sheet */
            $datas = [];
            foreach ($reader->getSheetIterator() as $sheet) {
                if ('INDICATEURS' === $sheet->getName()) {
                    foreach ($sheet->getRowIterator() as $row) {
                        $datas[] = $row->getCells();
                    }
                    break;
                }
            }
            $reader->close();

            return $datas;
        } else {
            return null;
        }
    }
```

But an exception occurs on `reader->open`

```
type: "https://tools.ietf.org/html/rfc2616#section-10"
title: "An error occurred"
status: 500
detail: "Could not open pj://foo/bar/myFile.xlsx for reading! Stream wrapper used is not supported for this type of file."
class: "Box\Spout\Common\Exception\IOException"
```

The exception thrown is defined as row 101 in *src/Spout/Reader/XLSX/Reader.php*

I don't know why :(

If u have an idea to help me or fix it, i thank you in advance.

2o1oo
